kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: tcc
  labels:
    type: local
    app: tcc-apps
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  capacity:
    storage: 12Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/kind/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - tcc-tls-control-plane
