kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-rh-dev
  namespace: tcc
  labels:
    type: local
    app: tcc-apps
spec:
  storageClassName: nfs-client 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
