kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-rh-dev
  namespace: tcc
  labels:
    type: local
    app: tcc-apps
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv
