name: Publish Docker image

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    types: [opened, closed, review_requested]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/sec-microservice-rh
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/sec-microservice-rh

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sec-microservice-rh:v0.1-latest,${{ secrets.DOCKER_HUB_USERNAME }}/sec-microservice-rh:v0.1-${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    
    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/scout-action@dd36f5b0295baffa006aa6623371f226cc03e506
      with:
        command: cves
        image: ${{ secrets.DOCKER_HUB_USERNAME }}/sec-microservice-rh:v0.1-${{ github.sha }}
        only-severities: critical,high
        exit-code: true
