name: Tests

on:
  pull_request:
    types: [opened, review_requested]
  push:
    branches:
    - main
    - 'release/*'

jobs:
  test_with_container:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0  # a full history is required for pull request analysis
    - name: Build test container
      run: |
        docker compose up postgres-test api-test && docker compose wait api-test
    - run: echo "Tests returned exit code 0 (Passed)"
    - name: Ending container
      run: docker compose down
    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: py-coverage-data
        path: ./.qodana/code-coverage
    - name: Use Qodana
      uses: JetBrains/qodana-action@v2023.3
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
      with:
        args: "-i,backend,--linter,jetbrains/qodana-python:2023.3-eap"
        pr-mode: false

        
